"""Read the JSON contract generated by tbls."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, cast

from metadata_pipeline.ports.schema_source import (
    ColumnSchema,
    DatabaseSchema,
    RelationSchema,
    SchemaSourceError,
    TableSchema,
)


class _SchemaContractError(ValueError):
    """Internal error carrying a precise JSON field path."""


class _Named(Protocol):
    """Structural type for schema objects that have a name."""

    @property
    def name(self) -> str:
        """Return the object name."""


@dataclass(frozen=True)
class TblsSchemaSource:
    """Load a provider-neutral database schema from tbls ``schema.json``."""

    path: Path

    def load(self) -> DatabaseSchema:
        """Read, validate, and convert the tbls JSON document."""
        try:
            payload: object = json.loads(self.path.read_text(encoding="utf-8"))
        except FileNotFoundError as error:
            raise SchemaSourceError(f"{self.path}: file not found") from error
        except json.JSONDecodeError as error:
            raise SchemaSourceError(
                f"{self.path}: line {error.lineno}, column {error.colno}: invalid JSON"
            ) from error
        except OSError as error:
            raise SchemaSourceError(f"{self.path}: unable to read file: {error}") from error

        try:
            return _parse_database_schema(payload)
        except _SchemaContractError as error:
            raise SchemaSourceError(f"{self.path}: {error}") from error


def _parse_database_schema(payload: object) -> DatabaseSchema:
    root = _mapping(payload, "$")
    name = _required_string(root, "name", "$")
    description = _optional_string(root, "desc", "$")
    table_values = _required_list(root, "tables", "$")
    relation_values = _optional_list(root, "relations", "$")

    tables = tuple(
        _parse_table(value, f"tables[{index}]") for index, value in enumerate(table_values)
    )
    relations = tuple(
        _parse_relation(value, f"relations[{index}]") for index, value in enumerate(relation_values)
    )
    _validate_references(tables, relations)

    return DatabaseSchema(
        name=name,
        description=description,
        tables=tables,
        relations=relations,
    )


def _parse_table(payload: object, field_path: str) -> TableSchema:
    value = _mapping(payload, field_path)
    column_values = _required_list(value, "columns", field_path)
    columns = tuple(
        _parse_column(column, f"{field_path}.columns[{index}]")
        for index, column in enumerate(column_values)
    )
    _reject_duplicate_names(columns, f"{field_path}.columns")

    return TableSchema(
        name=_required_string(value, "name", field_path),
        table_type=_required_string(value, "type", field_path),
        comment=_optional_string(value, "comment", field_path),
        columns=columns,
    )


def _parse_column(payload: object, field_path: str) -> ColumnSchema:
    value = _mapping(payload, field_path)
    return ColumnSchema(
        name=_required_string(value, "name", field_path),
        data_type=_required_string(value, "type", field_path),
        nullable=_required_bool(value, "nullable", field_path),
        comment=_optional_string(value, "comment", field_path),
    )


def _parse_relation(payload: object, field_path: str) -> RelationSchema:
    value = _mapping(payload, field_path)
    columns = _required_string_tuple(value, "columns", field_path)
    parent_columns = _required_string_tuple(value, "parent_columns", field_path)
    if len(columns) != len(parent_columns):
        raise _SchemaContractError(
            f"{field_path}.parent_columns: expected {len(columns)} column(s), "
            f"found {len(parent_columns)}"
        )

    return RelationSchema(
        table=_required_string(value, "table", field_path),
        columns=columns,
        parent_table=_required_string(value, "parent_table", field_path),
        parent_columns=parent_columns,
        definition=_required_string(value, "def", field_path),
        virtual=_optional_bool(value, "virtual", field_path, default=False),
    )


def _validate_references(
    tables: tuple[TableSchema, ...], relations: tuple[RelationSchema, ...]
) -> None:
    _reject_duplicate_names(tables, "tables")
    table_columns = {table.name: {column.name for column in table.columns} for table in tables}

    for index, relation in enumerate(relations):
        relation_path = f"relations[{index}]"
        _require_table(table_columns, relation.table, f"{relation_path}.table")
        _require_table(table_columns, relation.parent_table, f"{relation_path}.parent_table")
        _require_columns(
            table_columns[relation.table], relation.columns, f"{relation_path}.columns"
        )
        _require_columns(
            table_columns[relation.parent_table],
            relation.parent_columns,
            f"{relation_path}.parent_columns",
        )


def _reject_duplicate_names(values: tuple[_Named, ...], field_path: str) -> None:
    names: set[str] = set()
    for index, value in enumerate(values):
        name = value.name
        if name in names:
            raise _SchemaContractError(f"{field_path}[{index}].name: duplicate value {name!r}")
        names.add(name)


def _require_table(table_columns: dict[str, set[str]], table: str, field_path: str) -> None:
    if table not in table_columns:
        raise _SchemaContractError(f"{field_path}: unknown table {table!r}")


def _require_columns(available: set[str], columns: tuple[str, ...], field_path: str) -> None:
    for index, column in enumerate(columns):
        if column not in available:
            raise _SchemaContractError(f"{field_path}[{index}]: unknown column {column!r}")


def _mapping(value: object, field_path: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise _SchemaContractError(f"{field_path}: expected object")
    return cast(dict[str, object], value)


def _required_list(value: dict[str, object], field: str, field_path: str) -> list[object]:
    if field not in value:
        raise _SchemaContractError(f"{field_path}.{field}: missing required field")
    return _list(value[field], f"{field_path}.{field}")


def _optional_list(value: dict[str, object], field: str, field_path: str) -> list[object]:
    if field not in value:
        return []
    return _list(value[field], f"{field_path}.{field}")


def _list(value: object, field_path: str) -> list[object]:
    if not isinstance(value, list):
        raise _SchemaContractError(f"{field_path}: expected array")
    return cast(list[object], value)


def _required_string(value: dict[str, object], field: str, field_path: str) -> str:
    if field not in value:
        raise _SchemaContractError(f"{field_path}.{field}: missing required field")
    result = value[field]
    if not isinstance(result, str) or not result.strip():
        raise _SchemaContractError(f"{field_path}.{field}: expected non-empty string")
    return result


def _optional_string(value: dict[str, object], field: str, field_path: str) -> str:
    if field not in value:
        return ""
    result = value[field]
    if not isinstance(result, str):
        raise _SchemaContractError(f"{field_path}.{field}: expected string")
    return result


def _required_bool(value: dict[str, object], field: str, field_path: str) -> bool:
    if field not in value:
        raise _SchemaContractError(f"{field_path}.{field}: missing required field")
    result = value[field]
    if not isinstance(result, bool):
        raise _SchemaContractError(f"{field_path}.{field}: expected boolean")
    return result


def _optional_bool(value: dict[str, object], field: str, field_path: str, *, default: bool) -> bool:
    if field not in value:
        return default
    result = value[field]
    if not isinstance(result, bool):
        raise _SchemaContractError(f"{field_path}.{field}: expected boolean")
    return result


def _required_string_tuple(
    value: dict[str, object], field: str, field_path: str
) -> tuple[str, ...]:
    items = _required_list(value, field, field_path)
    if not items:
        raise _SchemaContractError(f"{field_path}.{field}: expected at least one item")

    result: list[str] = []
    for index, item in enumerate(items):
        if not isinstance(item, str) or not item.strip():
            raise _SchemaContractError(f"{field_path}.{field}[{index}]: expected non-empty string")
        result.append(item)
    return tuple(result)
