"""Application services for reviewer contract export and validation."""

from __future__ import annotations

import json
from pathlib import Path

from metadata_pipeline.adapters.schema.tbls_json import TblsSchemaSource
from metadata_pipeline.domain.review import ReviewDocument
from metadata_pipeline.io.review_yaml import (
    ReviewFileError,
    load_review_contract,
    load_review_document,
)
from metadata_pipeline.ports.schema_source import SchemaSourceError
from metadata_pipeline.validation.review import ValidationIssue, validate_review_document


def export_review_json_schema(output: Path) -> None:
    """Write the deterministic JSON Schema generated by the Pydantic model."""
    schema = ReviewDocument.model_json_schema(mode="validation")
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = (
        "https://raw.githubusercontent.com/ITHealer/metadata-repository/"
        "main/schemas/reviewer_metadata.schema.json"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def validate_review_directory(
    schema_path: Path,
    review_dir: Path,
    contract_path: Path,
) -> tuple[ValidationIssue, ...]:
    """Validate every reviewer YAML document against tbls technical schema."""
    issues: list[ValidationIssue] = []
    try:
        schema = TblsSchemaSource(schema_path).load()
    except SchemaSourceError as error:
        return (ValidationIssue("invalid_schema_source", schema_path, "$", str(error)),)

    try:
        contract = load_review_contract(contract_path)
    except ReviewFileError as error:
        return tuple(
            ValidationIssue("invalid_contract", error.path, issue.field, issue.message)
            for issue in error.issues
        )

    review_paths = sorted((*review_dir.glob("*.yml"), *review_dir.glob("*.yaml")))
    if not review_paths:
        return (
            ValidationIssue(
                "missing_review_files",
                review_dir,
                "$",
                "no .yml or .yaml reviewer files found",
            ),
        )

    reviews: list[tuple[Path, ReviewDocument]] = []
    for path in review_paths:
        try:
            reviews.append((path, load_review_document(path)))
        except ReviewFileError as error:
            issues.extend(
                ValidationIssue("invalid_review_document", path, issue.field, issue.message)
                for issue in error.issues
            )

    seen_tables: dict[str, Path] = {}
    for path, review in reviews:
        previous = seen_tables.get(review.table)
        if previous is not None:
            issues.append(
                ValidationIssue(
                    "duplicate_review_table",
                    path,
                    "table",
                    f"table {review.table!r} is already reviewed by {previous}",
                )
            )
        else:
            seen_tables[review.table] = path
        issues.extend(validate_review_document(schema, review, contract, path))

    raw_tables = {table.name for table in schema.tables}
    for missing_table in sorted(raw_tables - set(seen_tables)):
        issues.append(
            ValidationIssue(
                "missing_table_review",
                review_dir,
                missing_table,
                f"table {missing_table!r} has no reviewer metadata file",
            )
        )
    return tuple(issues)
